/**
 * create the prefix comment of the generated file
 * @descCN 创建生成文件的注释前缀，用于禁用eslint、prettier、oxlint、biome等检查
 * @param disabledTSCheck whether disabled ts-check
 */
export function createPrefixCommentOfGenFile(disabledTSCheck = false) {
  const prefix = `/* eslint-disable */`;
  let comment = `/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by unplugin-react-router
// Read more: https://github.com/sankeyangshu/unplugin-react-router
// This is an automatically generated file, please do not modify it manually. If you need to modify it, please modify it in the routing configuration file.
// 这是自动生成的文件，请不要手动修改，如果需要修改，请在路由配置文件中进行修改`;

  if (disabledTSCheck) {
    comment = `// @ts-nocheck\n${comment}`;
  }

  comment = `${prefix}\n${comment}`;

  return comment;
}
