/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by unplugin-react-router
// Read more: https://github.com/sankeyangshu/unplugin-react-router
// This is an automatically generated file, please do not modify it manually. If you need to modify it, please modify it in the routing configuration file.
// 这是自动生成的文件，请不要手动修改，如果需要修改，请在路由配置文件中进行修改

import type { RouteFileKey, RouteLayoutKey } from "@unplugin-react-router/types";

export const layouts: Record<RouteLayoutKey, () => Promise<any>> = {
  base: () => import("@/layouts/base/index"),
  blank: () => import("@/layouts/blank/index"),
};

export const pages: Record<RouteFileKey, () => Promise<any>> = {
  404: () => import("@/pages/(builtin)/404/index"),
  Home: () => import("@/pages/home/index"),
  HomeChild: () => import("@/pages/home/child"),
  HomeChild2: () => import("@/pages/home/child2"),
  List: () => import("@/pages/list/index"),
  ListAdd: () => import("@/pages/list/add"),
  ListDetail2IdUserId: () => import("@/pages/list/detail2-[[id]]-[[userId]]"),
  ListDetailIdUserId: () => import("@/pages/list/detail_[id]_[userId]"),
  ListEditId: () => import("@/pages/list/edit_[id]"),
  ListId: () => import("@/pages/list/[id]"),
  Login: () => import("@/pages/(builtin)/login/index"),
  Wip: () => import("@/pages/(builtin)/wip"),
};
