/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by unplugin-react-router
// Read more: https://github.com/sankeyangshu/unplugin-react-router
// This is an automatically generated file, please do not modify it manually. If you need to modify it, please modify it in the routing configuration file.
// 这是自动生成的文件，请不要手动修改，如果需要修改，请在路由配置文件中进行修改

import type { RouteKey, RoutePathMap } from '@unplugin-react-router/types';

/**
 * map of route name and route path
 */
const routePathMap: RoutePathMap = {
  "Root": "/",
  "NotFound": "*",
  "404": "/404",
  "Home": "/home",
  "HomeChild": "/home/child",
  "HomeChild2": "/home/child2",
  "List": "/list",
  "ListAdd": "/list/add",
  "ListDetail2IdUserId": "/list/detail2-:id?-:userId?",
  "ListDetailIdUserId": "/list/detail/:id/:userId",
  "ListEditId": "/list/edit/:id",
  "ListId": "/list/:id",
  "Login": "/login",
  "Wip": "/wip",
};

/**
 * get route path by route key
 * @param key route key
 */
export function getRoutePath(key: RouteKey) {
  return routePathMap[key];
}
