/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by unplugin-react-router
// Read more: https://github.com/sankeyangshu/unplugin-react-router
// This is an automatically generated file, please do not modify it manually. If you need to modify it, please modify it in the routing configuration file.
// 这是自动生成的文件，请不要手动修改，如果需要修改，请在路由配置文件中进行修改

import { redirect } from 'react-router';
import type { AutoRouterRoute } from '@unplugin-react-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: 'Root',
    path: '/',
    index: true,
    loader: () => redirect('/home'),
  },
  {
    name: 'NotFound',
    path: '*',
    layout: 'base',
    component: '404',
  },
  {
    name: '404',
    path: '/404',
    layout: 'base',
    component: '404',
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
  },
  {
    name: 'HomeChild',
    path: '/home/child',
    layout: 'blank',
    component: 'HomeChild',
  },
  {
    name: 'HomeChild2',
    path: '/home/child2',
    layout: 'base',
    component: 'HomeChild2',
  },
  {
    name: 'List',
    path: '/list',
    layout: 'base',
    component: 'List',
  },
  {
    name: 'ListAdd',
    path: '/list/add',
    layout: 'base',
    component: 'ListAdd',
  },
  {
    name: 'ListDetail2IdUserId',
    path: '/list/detail2-:id?-:userId?',
    layout: 'base',
    component: 'ListDetail2IdUserId',
  },
  {
    name: 'ListDetailIdUserId',
    path: '/list/detail/:id/:userId',
    layout: 'base',
    component: 'ListDetailIdUserId',
  },
  {
    name: 'ListEditId',
    path: '/list/edit/:id',
    layout: 'base',
    component: 'ListEditId',
  },
  {
    name: 'ListId',
    path: '/list/:id',
    layout: 'base',
    component: 'ListId',
  },
  {
    name: 'Login',
    path: '/login',
    layout: 'base',
    component: 'Login',
  },
  {
    name: 'Wip',
    path: '/wip',
    layout: 'base',
    component: 'Wip',
  }
];
