/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by unplugin-react-router
// Read more: https://github.com/sankeyangshu/unplugin-react-router
// This is an automatically generated file, please do not modify it manually. If you need to modify it, please modify it in the routing configuration file.
// 这是自动生成的文件，请不要手动修改，如果需要修改，请在路由配置文件中进行修改

import type { RouteObject } from 'react-router';
import type {
  AutoRouterRedirect,
  AutoRouterRoute,
  AutoRouterView,
  RouteFileKey,
  RouteLayoutKey
} from '@unplugin-react-router/types';

function isAutoRouterRedirect(route: AutoRouterRoute): route is AutoRouterRedirect {
  return route?.index === true;
}

function getFormattedRoutes(routes: AutoRouterRoute[]) {
  const groupedRoutes = new Map<RouteLayoutKey, AutoRouterView[]>();
  const redirects: AutoRouterRedirect[] = [];

  routes.forEach(route => {
    if (isAutoRouterRedirect(route)) {
      redirects.push(route);
      return;
    }

    const items = groupedRoutes.get(route.layout) || [];
    items.push(route);
    groupedRoutes.set(route.layout, items);
  });

  return {
    redirects,
    groupedRoutes
  };
}

export function transformToReactRoutes(
  routes: AutoRouterRoute[],
  layouts: Record<RouteLayoutKey, () => Promise<any>>,
  pages: Record<RouteFileKey, () => Promise<any>>
) {
  const { redirects, groupedRoutes } = getFormattedRoutes(routes);

  const reactRoutes: RouteObject[] = [...redirects];

  // Convert route config, simplifying the logic for actions, loader, etc.
  function convertConfig(m: any) {
    const { action, loader, shouldRevalidate, default: Component } = m;
    return {
      action, // always use action
      loader, // always use loader
      shouldRevalidate,
      Component,
    };
  }

  groupedRoutes.forEach((items, layout) => {
    // 分离特殊路由和普通路由
    const specialRoutes: AutoRouterView[] = [];
    const normalRoutes: AutoRouterView[] = [];
    
    items.forEach(item => {
      // 通配符路由直接添加到根级别
      if (item.path === '*') {
        specialRoutes.push(item);
      } else {
        normalRoutes.push(item);
      }
    });
    
    // 特殊路由直接添加到根级别
    specialRoutes.forEach(item => {
      const { layout: _, component, ...rest } = item;
      reactRoutes.push({
        ...rest,
        lazy: async () => {
          const config = await pages[component]();
          return {
            ...convertConfig(config),
          };
        },
      });
    });
    
    // 普通路由作为布局的子路由
    if (normalRoutes.length > 0) {
      const layoutRoute: RouteObject = {
        path: '/',
        lazy: async () => {
          const config = await layouts[layout]();

          return {
            ...convertConfig(config),
          };
        },
        children: normalRoutes.map(item => {
          const { layout: _, component, path, ...rest } = item;
          
          // 将绝对路径转换为相对路径（去掉开头的/）
          const relativePath = path.startsWith('/') ? path.slice(1) : path;

          return {
            ...rest,
            path: relativePath,
            lazy: async () => {
              const config = await pages[component]();
              return {
                ...convertConfig(config),
              };
            },
          };
        })
      };

      reactRoutes.push(layoutRoute);
    }
  });

  return reactRoutes;
}
