/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by unplugin-react-router
// Read more: https://github.com/sankeyangshu/unplugin-react-router
// This is an automatically generated file, please do not modify it manually. If you need to modify it, please modify it in the routing configuration file.
// 这是自动生成的文件，请不要手动修改，如果需要修改，请在路由配置文件中进行修改

declare module "@unplugin-react-router/types" {
  type IndexRouteObject = import("react-router").IndexRouteObject;
  type NonIndexRouteObject = import("react-router").NonIndexRouteObject;

  /**
   * route layout key
   */
  export type RouteLayoutKey = "base" | "blank";

  /**
   * route path map
   */
  export type RoutePathMap = {
    "Root": "/";
    "NotFound": "*";
    "404": "/404";
    "Home": "/home";
    "HomeChild": "/home/child";
    "HomeChild2": "/home/child2";
    "List": "/list";
    "ListAdd": "/list/add";
    "ListDetail2IdUserId": "/list/detail2-:id?-:userId?";
    "ListDetailIdUserId": "/list/detail/:id/:userId";
    "ListEditId": "/list/edit/:id";
    "ListId": "/list/:id";
    "Login": "/login";
    "Wip": "/wip";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RoutePathMap;

  /**
   * route path
   */
  export type RoutePath = RoutePathMap[RouteKey];

  /**
   * root route key
   */
  export type RootRouteKey = 'Root';

  /**
   * not found route key
   */
  export type NotFoundRouteKey = 'NotFound';

  /**
   * builtin route key
   */
  export type BuiltinRouteKey = RootRouteKey | NotFoundRouteKey;

  /**
   * reuse route key
   */
  export type ReuseRouteKey = never;

  /**
   * the route file key, which has it's own file
   */
  export type RouteFileKey = Exclude<RouteKey, BuiltinRouteKey | ReuseRouteKey>;

  /**
   * mapped name and path
   */
  type MappedNamePath = {
    [K in RouteKey]: { name: K; path: RoutePathMap[K] };
  }[RouteKey];

  /**
   * auto router view
   */
  export type AutoRouterView = Omit<NonIndexRouteObject, 'children' | 'id' | 'path'> & {
    component: RouteFileKey;
    layout: RouteLayoutKey;
  } & MappedNamePath;

  /**
   * auto router redirect
   */
  export type AutoRouterRedirect = Omit<IndexRouteObject, 'children' | 'id' | 'path'> & MappedNamePath;

  /**
   * auto router route
   */
  export type AutoRouterRoute = AutoRouterView | AutoRouterRedirect;
}
